### ISSUE TITLE
NPE removing projects in eclipse plugin 

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind-eclipse#156]
I am running the tech preview 0.2.0 on Mac and see this exception when removing projects from codewind. Have seen it for Go and Java Lagom apps:

java.lang.NullPointerException
	at org.eclipse.codewind.filewatchers.eclipse.CodewindResourceChangeListener.resourceChanged(CodewindResourceChangeListener.java:43)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:305)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:295)
	at org.eclipse.core.internal.events.NotificationManager.handleEvent(NotificationManager.java:271)
	at org.eclipse.core.internal.resources.Workspace.broadcastEvent(Workspace.java:374)
	at org.eclipse.core.internal.resources.Resource.broadcastPreDeleteEvent(Resource.java:1826)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:737)
	at org.eclipse.core.internal.resources.Project.delete(Project.java:322)

The remove still appears to work.

**Comment by jgwest** [comment]
I'll handle this.

**Comment by eharris369** [comment]
Fixed by PR #167
