### ISSUE TITLE
SVT : Node project not fully deleted on windows O/S

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind-eclipse#245]
Running the eclipse plugin on windows O/S

Codewind version:   Codewind tech preview	0.3.0.v201908281310	
Eclipse IDE : Eclipse IDE for committers :  2019-06 (4.12.0)

To reproduce
1. Create a Node project
2. Remove the Node project and check to also delete from disk.

The project directory is not removed from the disk and contains a single .project file. This is the content of the file:

<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>SVTAddExistingNodeProject1</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
	</buildSpec>
	<natures>
	</natures>
</projectDescription>

**Comment by mmulholl** [comment]
@eraharris369 it stays in the Project Explorer. 

Got these exceptions in the console.log:

!MESSAGE [ERROR UnbindProjectAction$2.run:122] Error requesting application remove: SVTNodeProject1
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Problems encountered while deleting resources.
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:765)
	at org.eclipse.core.internal.resources.Project.delete(Project.java:322)
	at org.eclipse.codewind.ui.internal.actions.UnbindProjectAction$2.run(UnbindProjectAction.java:116)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Contains: Could not delete 'C:\codewind-workspace\SVTNodeProject1'.
org.eclipse.core.runtime.CoreException: Problems encountered while deleting files.
	at org.eclipse.core.internal.filesystem.local.LocalFile.delete(LocalFile.java:142)
	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteProject(ResourceTree.java:446)
	at org.eclipse.core.internal.resources.ResourceTree.standardDeleteProject(ResourceTree.java:853)
	at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1775)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:752)
	at org.eclipse.core.internal.resources.Project.delete(Project.java:322)
	at org.eclipse.codewind.ui.internal.actions.UnbindProjectAction$2.run(UnbindProjectAction.java:116)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Contains: Could not delete: C:\codewind-workspace\SVTNodeProject1.
java.nio.file.DirectoryNotEmptyException: C:\codewind-workspace\SVTNodeProject1
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
	at java.nio.file.Files.deleteIfExists(Unknown Source)
	at org.eclipse.core.internal.filesystem.local.LocalFile.internalDelete(LocalFile.java:256)
	at org.eclipse.core.internal.filesystem.local.LocalFile.delete(LocalFile.java:140)
	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteProject(ResourceTree.java:446)
	at org.eclipse.core.internal.resources.ResourceTree.standardDeleteProject(ResourceTree.java:853)
	at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1775)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:752)
	at org.eclipse.core.internal.resources.Project.delete(Project.java:322)
	at org.eclipse.codewind.ui.internal.actions.UnbindProjectAction$2.run(UnbindProjectAction.java:116)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Contains: Could not delete 'C:\codewind-workspace\SVTNodeProject1'.

etc.

**Comment by eharris369** [comment]
This should be fixed.  I forgot this was open and fixed it under #285.

**Comment by eharris369** [comment]
Closing this as it is covered under https://github.com/eclipse/codewind/issues/469
