### ISSUE TITLE
[Eclipse 541220] Created a go project, got a dialog about an NPE

### ISSUE THREAD

**Issue by jopit** [eclipse/codewind-eclipse#89]
I created a go project, and I got a dialog which said `java.lang.NullPointerException`.  Looking at the eclipse log file, I see the following
```
!ENTRY org.eclipse.ui.ide 4 0 2019-06-24 15:58:19.179
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.eclipse.jst.ws.jaxrs.ui.internal.importer.JaxRsConfigurator.canConfigure(JaxRsConfigurator.java:67)
	at org.eclipse.ui.internal.wizards.datatransfer.SmartImportJob.importProjectAndChildrenRecursively(SmartImportJob.java:506)
	at org.eclipse.ui.internal.wizards.datatransfer.SmartImportJob.run(SmartImportJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
However, nothing seems to be broken by this as far as I can tell.

Eclipse Version: 2019-03 (4.11.0)

Here's the full log.
[log.txt](https://github.com/eclipse/codewind-eclipse/files/3322409/log.txt)

**Comment by eharris369** [comment]
I found this Eclipse bug with the same stack trace: https://bugs.eclipse.org/bugs/show_bug.cgi?id=541220

**Comment by keithchong** [comment]
Target is WTP 3.15.  Gerrit change has been created.

**Comment by cccanderson** [comment]
This has been fixed for the September release of WTP.

**Comment by eharris369** [comment]
@jopit Since this has been fixed in Eclipse, can this issue be closed?
